Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/EachWithObject:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'db/**/*'
